include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"


variables:
    # chunk_size here forces multiple chunks even for test data which better exercises some channels
    NF_WORKFLOW_OPTS: "--fastq test_data/fastq --reference_based_assembly --reference test_data/ref/reference.subseq.fa.gz --threads 4 --chunk_size 100000"
    NF_IGNORE_PROCESSES: "deNovo,runProkka"
    CI_FLAVOUR: "new"
    PYTEST_CONTAINER_NAME: "wf-bacterial-genomes"
    NF_PROCESS_FILES: "main.nf wf-bacterial-genomes/main.nf"
    GIT_SUBMODULE_STRATEGY: recursive


docker-run:
    parallel:
        matrix:
            - MATRIX_NAME: ["isolates"]
              TAG: [large_ram]
    tags:
        - $TAG
    rules:
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "isolates"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq --reference_based_assembly --reference test_data/ref/reference.subseq.fa.gz --threads 4 --chunk_size 100000 --isolates"
              NF_IGNORE_PROCESSES: "deNovo,runProkka"

# reminder: update AUX_IMAGE_TAG if the aux container package versions are changed
release-prokka:
    extends: .aux-container
    variables:
        AUX_IMAGE_NAME: "prokka"
        AUX_IMAGE_ENVFILE: "environment_prokka.yaml"
        AUX_IMAGE_TAG: "1.14.5"
